use axum::body::Body;
use axum::http::{Request, StatusCode};
use axum::Router;
use http_body_util::BodyExt;
use std::collections::VecDeque;
use std::sync::{Arc, Mutex};
use tower::ServiceExt;

use opencrab_llm::message::*;
use opencrab_llm::router::LlmRouter;
use opencrab_llm::traits::LlmProvider;
use opencrab_server::{create_router, AppState};

include!("api_e2e/support.rs");
include!("api_e2e/agents_sessions_memory.rs");
include!("api_e2e/discord_owner_identity.rs");
include!("api_e2e/llm_support.rs");
include!("api_e2e/llm_conversation.rs");
include!("api_e2e/import_api.rs");
include!("api_e2e/provider_voice_setup.rs");
include!("api_e2e/skill_consolidation.rs");
include!("api_e2e/rest_dispatch.rs");
include!("api_e2e/rest_subtask_cancellation.rs");
include!("api_e2e/subtask_dispatch.rs");
include!("api_e2e/nostr_security.rs");
include!("api_e2e/dialogue_evaluator.rs");
include!("api_e2e/model_pricing.rs");
include!("api_e2e/tool_logs.rs");
include!("api_e2e/turn_continuation.rs");
include!("api_e2e/no_reply_persistence.rs");
include!("api_e2e/system_prompt_tool_index.rs");
