[package]
name = "opencrab-discord"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
rusqlite = { workspace = true }
serenity = { workspace = true }
opencrab-core = { workspace = true }
opencrab-actions = { workspace = true }
opencrab-gateway = { workspace = true, features = ["discord"] }
opencrab-db = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
chrono = { workspace = true }
iana-time-zone = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
